[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = default.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -O1
    -DUCSD_USERNAME=\"\"
    -DUCSD_PASSWORD=\"\"
    -DWIFI_SSID=\"YourSSID\"
    -DNON_ENTERPRISE_WIFI_PASSWORD=\"YourPassword\"

lib_deps =
    sparkfun/SparkFun VL53L5CX Arduino Library
    knolleary/PubSubClient @ ^2.8